//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceSoft.serviciosWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.confesoft.pucp.du.pe/", ConfigurationName="serviciosWS.ServiciosWS")]
    public interface ServiciosWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.confesoft.pucp.du.pe/ServiciosWS/listarEventosPorNombreRequest", ReplyAction="http://services.confesoft.pucp.du.pe/ServiciosWS/listarEventosPorNombreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConferenceSoft.serviciosWS.listarEventosPorNombreResponse listarEventosPorNombre(ConferenceSoft.serviciosWS.listarEventosPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.confesoft.pucp.du.pe/ServiciosWS/listarEventosPorNombreRequest", ReplyAction="http://services.confesoft.pucp.du.pe/ServiciosWS/listarEventosPorNombreResponse")]
        System.Threading.Tasks.Task<ConferenceSoft.serviciosWS.listarEventosPorNombreResponse> listarEventosPorNombreAsync(ConferenceSoft.serviciosWS.listarEventosPorNombreRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.confesoft.pucp.du.pe/ServiciosWS/insertarEventoRequest", ReplyAction="http://services.confesoft.pucp.du.pe/ServiciosWS/insertarEventoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConferenceSoft.serviciosWS.insertarEventoResponse insertarEvento(ConferenceSoft.serviciosWS.insertarEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.confesoft.pucp.du.pe/ServiciosWS/insertarEventoRequest", ReplyAction="http://services.confesoft.pucp.du.pe/ServiciosWS/insertarEventoResponse")]
        System.Threading.Tasks.Task<ConferenceSoft.serviciosWS.insertarEventoResponse> insertarEventoAsync(ConferenceSoft.serviciosWS.insertarEventoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.confesoft.pucp.du.pe/ServiciosWS/listarPonenciasPorIdEventoReques" +
            "t", ReplyAction="http://services.confesoft.pucp.du.pe/ServiciosWS/listarPonenciasPorIdEventoRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConferenceSoft.serviciosWS.listarPonenciasPorIdEventoResponse listarPonenciasPorIdEvento(ConferenceSoft.serviciosWS.listarPonenciasPorIdEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.confesoft.pucp.du.pe/ServiciosWS/listarPonenciasPorIdEventoReques" +
            "t", ReplyAction="http://services.confesoft.pucp.du.pe/ServiciosWS/listarPonenciasPorIdEventoRespon" +
            "se")]
        System.Threading.Tasks.Task<ConferenceSoft.serviciosWS.listarPonenciasPorIdEventoResponse> listarPonenciasPorIdEventoAsync(ConferenceSoft.serviciosWS.listarPonenciasPorIdEventoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.confesoft.pucp.du.pe/ServiciosWS/listarIntegrantesPorNombreTipoRe" +
            "quest", ReplyAction="http://services.confesoft.pucp.du.pe/ServiciosWS/listarIntegrantesPorNombreTipoRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConferenceSoft.serviciosWS.listarIntegrantesPorNombreTipoResponse listarIntegrantesPorNombreTipo(ConferenceSoft.serviciosWS.listarIntegrantesPorNombreTipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.confesoft.pucp.du.pe/ServiciosWS/listarIntegrantesPorNombreTipoRe" +
            "quest", ReplyAction="http://services.confesoft.pucp.du.pe/ServiciosWS/listarIntegrantesPorNombreTipoRe" +
            "sponse")]
        System.Threading.Tasks.Task<ConferenceSoft.serviciosWS.listarIntegrantesPorNombreTipoResponse> listarIntegrantesPorNombreTipoAsync(ConferenceSoft.serviciosWS.listarIntegrantesPorNombreTipoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.confesoft.pucp.du.pe/")]
    public partial class evento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descripcionField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int idEventoField;
        
        private string nombreField;
        
        private ponencia[] ponenciasField;
        
        private byte[] portadaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idEvento {
            get {
                return this.idEventoField;
            }
            set {
                this.idEventoField = value;
                this.RaisePropertyChanged("idEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ponencias", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public ponencia[] ponencias {
            get {
                return this.ponenciasField;
            }
            set {
                this.ponenciasField = value;
                this.RaisePropertyChanged("ponencias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=6)]
        public byte[] portada {
            get {
                return this.portadaField;
            }
            set {
                this.portadaField = value;
                this.RaisePropertyChanged("portada");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.confesoft.pucp.du.pe/")]
    public partial class ponencia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string horaFinField;
        
        private string horaInicioField;
        
        private int idPonenciaField;
        
        private integrante ponenteField;
        
        private string tituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string horaFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
                this.RaisePropertyChanged("horaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string horaInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
                this.RaisePropertyChanged("horaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idPonencia {
            get {
                return this.idPonenciaField;
            }
            set {
                this.idPonenciaField = value;
                this.RaisePropertyChanged("idPonencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public integrante ponente {
            get {
                return this.ponenteField;
            }
            set {
                this.ponenteField = value;
                this.RaisePropertyChanged("ponente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.confesoft.pucp.du.pe/")]
    public partial class integrante : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string apellidoPaternoField;
        
        private string codigoPUCPField;
        
        private int idIntegranteField;
        
        private string nombreField;
        
        private tipoIntegrante tipoIntegranteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoPUCP {
            get {
                return this.codigoPUCPField;
            }
            set {
                this.codigoPUCPField = value;
                this.RaisePropertyChanged("codigoPUCP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idIntegrante {
            get {
                return this.idIntegranteField;
            }
            set {
                this.idIntegranteField = value;
                this.RaisePropertyChanged("idIntegrante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoIntegrante tipoIntegrante {
            get {
                return this.tipoIntegranteField;
            }
            set {
                this.tipoIntegranteField = value;
                this.RaisePropertyChanged("tipoIntegrante");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.confesoft.pucp.du.pe/")]
    public partial class tipoIntegrante : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private int idTipoIntegranteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idTipoIntegrante {
            get {
                return this.idTipoIntegranteField;
            }
            set {
                this.idTipoIntegranteField = value;
                this.RaisePropertyChanged("idTipoIntegrante");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEventosPorNombre", WrapperNamespace="http://services.confesoft.pucp.du.pe/", IsWrapped=true)]
    public partial class listarEventosPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.confesoft.pucp.du.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarEventosPorNombreRequest() {
        }
        
        public listarEventosPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEventosPorNombreResponse", WrapperNamespace="http://services.confesoft.pucp.du.pe/", IsWrapped=true)]
    public partial class listarEventosPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.confesoft.pucp.du.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConferenceSoft.serviciosWS.evento[] @return;
        
        public listarEventosPorNombreResponse() {
        }
        
        public listarEventosPorNombreResponse(ConferenceSoft.serviciosWS.evento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEvento", WrapperNamespace="http://services.confesoft.pucp.du.pe/", IsWrapped=true)]
    public partial class insertarEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.confesoft.pucp.du.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConferenceSoft.serviciosWS.evento evento;
        
        public insertarEventoRequest() {
        }
        
        public insertarEventoRequest(ConferenceSoft.serviciosWS.evento evento) {
            this.evento = evento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEventoResponse", WrapperNamespace="http://services.confesoft.pucp.du.pe/", IsWrapped=true)]
    public partial class insertarEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.confesoft.pucp.du.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarEventoResponse() {
        }
        
        public insertarEventoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPonenciasPorIdEvento", WrapperNamespace="http://services.confesoft.pucp.du.pe/", IsWrapped=true)]
    public partial class listarPonenciasPorIdEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.confesoft.pucp.du.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEvento;
        
        public listarPonenciasPorIdEventoRequest() {
        }
        
        public listarPonenciasPorIdEventoRequest(int idEvento) {
            this.idEvento = idEvento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPonenciasPorIdEventoResponse", WrapperNamespace="http://services.confesoft.pucp.du.pe/", IsWrapped=true)]
    public partial class listarPonenciasPorIdEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.confesoft.pucp.du.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConferenceSoft.serviciosWS.ponencia[] @return;
        
        public listarPonenciasPorIdEventoResponse() {
        }
        
        public listarPonenciasPorIdEventoResponse(ConferenceSoft.serviciosWS.ponencia[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarIntegrantesPorNombreTipo", WrapperNamespace="http://services.confesoft.pucp.du.pe/", IsWrapped=true)]
    public partial class listarIntegrantesPorNombreTipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.confesoft.pucp.du.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.confesoft.pucp.du.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ushort tipo;
        
        public listarIntegrantesPorNombreTipoRequest() {
        }
        
        public listarIntegrantesPorNombreTipoRequest(string nombre, ushort tipo) {
            this.nombre = nombre;
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarIntegrantesPorNombreTipoResponse", WrapperNamespace="http://services.confesoft.pucp.du.pe/", IsWrapped=true)]
    public partial class listarIntegrantesPorNombreTipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.confesoft.pucp.du.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConferenceSoft.serviciosWS.integrante[] @return;
        
        public listarIntegrantesPorNombreTipoResponse() {
        }
        
        public listarIntegrantesPorNombreTipoResponse(ConferenceSoft.serviciosWS.integrante[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosWSChannel : ConferenceSoft.serviciosWS.ServiciosWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosWSClient : System.ServiceModel.ClientBase<ConferenceSoft.serviciosWS.ServiciosWS>, ConferenceSoft.serviciosWS.ServiciosWS {
        
        public ServiciosWSClient() {
        }
        
        public ServiciosWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConferenceSoft.serviciosWS.listarEventosPorNombreResponse ConferenceSoft.serviciosWS.ServiciosWS.listarEventosPorNombre(ConferenceSoft.serviciosWS.listarEventosPorNombreRequest request) {
            return base.Channel.listarEventosPorNombre(request);
        }
        
        public ConferenceSoft.serviciosWS.evento[] listarEventosPorNombre(string nombre) {
            ConferenceSoft.serviciosWS.listarEventosPorNombreRequest inValue = new ConferenceSoft.serviciosWS.listarEventosPorNombreRequest();
            inValue.nombre = nombre;
            ConferenceSoft.serviciosWS.listarEventosPorNombreResponse retVal = ((ConferenceSoft.serviciosWS.ServiciosWS)(this)).listarEventosPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConferenceSoft.serviciosWS.listarEventosPorNombreResponse> ConferenceSoft.serviciosWS.ServiciosWS.listarEventosPorNombreAsync(ConferenceSoft.serviciosWS.listarEventosPorNombreRequest request) {
            return base.Channel.listarEventosPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConferenceSoft.serviciosWS.listarEventosPorNombreResponse> listarEventosPorNombreAsync(string nombre) {
            ConferenceSoft.serviciosWS.listarEventosPorNombreRequest inValue = new ConferenceSoft.serviciosWS.listarEventosPorNombreRequest();
            inValue.nombre = nombre;
            return ((ConferenceSoft.serviciosWS.ServiciosWS)(this)).listarEventosPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConferenceSoft.serviciosWS.insertarEventoResponse ConferenceSoft.serviciosWS.ServiciosWS.insertarEvento(ConferenceSoft.serviciosWS.insertarEventoRequest request) {
            return base.Channel.insertarEvento(request);
        }
        
        public int insertarEvento(ConferenceSoft.serviciosWS.evento evento) {
            ConferenceSoft.serviciosWS.insertarEventoRequest inValue = new ConferenceSoft.serviciosWS.insertarEventoRequest();
            inValue.evento = evento;
            ConferenceSoft.serviciosWS.insertarEventoResponse retVal = ((ConferenceSoft.serviciosWS.ServiciosWS)(this)).insertarEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConferenceSoft.serviciosWS.insertarEventoResponse> ConferenceSoft.serviciosWS.ServiciosWS.insertarEventoAsync(ConferenceSoft.serviciosWS.insertarEventoRequest request) {
            return base.Channel.insertarEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConferenceSoft.serviciosWS.insertarEventoResponse> insertarEventoAsync(ConferenceSoft.serviciosWS.evento evento) {
            ConferenceSoft.serviciosWS.insertarEventoRequest inValue = new ConferenceSoft.serviciosWS.insertarEventoRequest();
            inValue.evento = evento;
            return ((ConferenceSoft.serviciosWS.ServiciosWS)(this)).insertarEventoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConferenceSoft.serviciosWS.listarPonenciasPorIdEventoResponse ConferenceSoft.serviciosWS.ServiciosWS.listarPonenciasPorIdEvento(ConferenceSoft.serviciosWS.listarPonenciasPorIdEventoRequest request) {
            return base.Channel.listarPonenciasPorIdEvento(request);
        }
        
        public ConferenceSoft.serviciosWS.ponencia[] listarPonenciasPorIdEvento(int idEvento) {
            ConferenceSoft.serviciosWS.listarPonenciasPorIdEventoRequest inValue = new ConferenceSoft.serviciosWS.listarPonenciasPorIdEventoRequest();
            inValue.idEvento = idEvento;
            ConferenceSoft.serviciosWS.listarPonenciasPorIdEventoResponse retVal = ((ConferenceSoft.serviciosWS.ServiciosWS)(this)).listarPonenciasPorIdEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConferenceSoft.serviciosWS.listarPonenciasPorIdEventoResponse> ConferenceSoft.serviciosWS.ServiciosWS.listarPonenciasPorIdEventoAsync(ConferenceSoft.serviciosWS.listarPonenciasPorIdEventoRequest request) {
            return base.Channel.listarPonenciasPorIdEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConferenceSoft.serviciosWS.listarPonenciasPorIdEventoResponse> listarPonenciasPorIdEventoAsync(int idEvento) {
            ConferenceSoft.serviciosWS.listarPonenciasPorIdEventoRequest inValue = new ConferenceSoft.serviciosWS.listarPonenciasPorIdEventoRequest();
            inValue.idEvento = idEvento;
            return ((ConferenceSoft.serviciosWS.ServiciosWS)(this)).listarPonenciasPorIdEventoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConferenceSoft.serviciosWS.listarIntegrantesPorNombreTipoResponse ConferenceSoft.serviciosWS.ServiciosWS.listarIntegrantesPorNombreTipo(ConferenceSoft.serviciosWS.listarIntegrantesPorNombreTipoRequest request) {
            return base.Channel.listarIntegrantesPorNombreTipo(request);
        }
        
        public ConferenceSoft.serviciosWS.integrante[] listarIntegrantesPorNombreTipo(string nombre, ushort tipo) {
            ConferenceSoft.serviciosWS.listarIntegrantesPorNombreTipoRequest inValue = new ConferenceSoft.serviciosWS.listarIntegrantesPorNombreTipoRequest();
            inValue.nombre = nombre;
            inValue.tipo = tipo;
            ConferenceSoft.serviciosWS.listarIntegrantesPorNombreTipoResponse retVal = ((ConferenceSoft.serviciosWS.ServiciosWS)(this)).listarIntegrantesPorNombreTipo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConferenceSoft.serviciosWS.listarIntegrantesPorNombreTipoResponse> ConferenceSoft.serviciosWS.ServiciosWS.listarIntegrantesPorNombreTipoAsync(ConferenceSoft.serviciosWS.listarIntegrantesPorNombreTipoRequest request) {
            return base.Channel.listarIntegrantesPorNombreTipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConferenceSoft.serviciosWS.listarIntegrantesPorNombreTipoResponse> listarIntegrantesPorNombreTipoAsync(string nombre, ushort tipo) {
            ConferenceSoft.serviciosWS.listarIntegrantesPorNombreTipoRequest inValue = new ConferenceSoft.serviciosWS.listarIntegrantesPorNombreTipoRequest();
            inValue.nombre = nombre;
            inValue.tipo = tipo;
            return ((ConferenceSoft.serviciosWS.ServiciosWS)(this)).listarIntegrantesPorNombreTipoAsync(inValue);
        }
    }
}
