//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinconLibroSoft.ServiciosWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.rinconlibrosoft.pucp.edu.pe/", ConfigurationName="ServiciosWS.ServiciosWS")]
    public interface ServiciosWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/listarEditorialPorNombreR" +
            "equest", ReplyAction="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/listarEditorialPorNombreR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RinconLibroSoft.ServiciosWS.listarEditorialPorNombreResponse listarEditorialPorNombre(RinconLibroSoft.ServiciosWS.listarEditorialPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/listarEditorialPorNombreR" +
            "equest", ReplyAction="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/listarEditorialPorNombreR" +
            "esponse")]
        System.Threading.Tasks.Task<RinconLibroSoft.ServiciosWS.listarEditorialPorNombreResponse> listarEditorialPorNombreAsync(RinconLibroSoft.ServiciosWS.listarEditorialPorNombreRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/listarLibrosPorTituloOEdi" +
            "torialRequest", ReplyAction="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/listarLibrosPorTituloOEdi" +
            "torialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RinconLibroSoft.ServiciosWS.listarLibrosPorTituloOEditorialResponse listarLibrosPorTituloOEditorial(RinconLibroSoft.ServiciosWS.listarLibrosPorTituloOEditorialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/listarLibrosPorTituloOEdi" +
            "torialRequest", ReplyAction="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/listarLibrosPorTituloOEdi" +
            "torialResponse")]
        System.Threading.Tasks.Task<RinconLibroSoft.ServiciosWS.listarLibrosPorTituloOEditorialResponse> listarLibrosPorTituloOEditorialAsync(RinconLibroSoft.ServiciosWS.listarLibrosPorTituloOEditorialRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/listarAutoresPorIdLibroRe" +
            "quest", ReplyAction="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/listarAutoresPorIdLibroRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RinconLibroSoft.ServiciosWS.listarAutoresPorIdLibroResponse listarAutoresPorIdLibro(RinconLibroSoft.ServiciosWS.listarAutoresPorIdLibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/listarAutoresPorIdLibroRe" +
            "quest", ReplyAction="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/listarAutoresPorIdLibroRe" +
            "sponse")]
        System.Threading.Tasks.Task<RinconLibroSoft.ServiciosWS.listarAutoresPorIdLibroResponse> listarAutoresPorIdLibroAsync(RinconLibroSoft.ServiciosWS.listarAutoresPorIdLibroRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/listarAutoresPorNombreReq" +
            "uest", ReplyAction="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/listarAutoresPorNombreRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RinconLibroSoft.ServiciosWS.listarAutoresPorNombreResponse listarAutoresPorNombre(RinconLibroSoft.ServiciosWS.listarAutoresPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/listarAutoresPorNombreReq" +
            "uest", ReplyAction="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/listarAutoresPorNombreRes" +
            "ponse")]
        System.Threading.Tasks.Task<RinconLibroSoft.ServiciosWS.listarAutoresPorNombreResponse> listarAutoresPorNombreAsync(RinconLibroSoft.ServiciosWS.listarAutoresPorNombreRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/helloRequest", ReplyAction="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RinconLibroSoft.ServiciosWS.helloResponse hello(RinconLibroSoft.ServiciosWS.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/helloRequest", ReplyAction="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/helloResponse")]
        System.Threading.Tasks.Task<RinconLibroSoft.ServiciosWS.helloResponse> helloAsync(RinconLibroSoft.ServiciosWS.helloRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/insertarLibroRequest", ReplyAction="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/insertarLibroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RinconLibroSoft.ServiciosWS.insertarLibroResponse insertarLibro(RinconLibroSoft.ServiciosWS.insertarLibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/insertarLibroRequest", ReplyAction="http://services.rinconlibrosoft.pucp.edu.pe/ServiciosWS/insertarLibroResponse")]
        System.Threading.Tasks.Task<RinconLibroSoft.ServiciosWS.insertarLibroResponse> insertarLibroAsync(RinconLibroSoft.ServiciosWS.insertarLibroRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.rinconlibrosoft.pucp.edu.pe/")]
    public partial class editorial : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idEditorialField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idEditorial {
            get {
                return this.idEditorialField;
            }
            set {
                this.idEditorialField = value;
                this.RaisePropertyChanged("idEditorial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.rinconlibrosoft.pucp.edu.pe/")]
    public partial class autor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string apellidoPaternoField;
        
        private int idAutorField;
        
        private string nacionalidadField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idAutor {
            get {
                return this.idAutorField;
            }
            set {
                this.idAutorField = value;
                this.RaisePropertyChanged("idAutor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
                this.RaisePropertyChanged("nacionalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.rinconlibrosoft.pucp.edu.pe/")]
    public partial class libro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private autor[] autoresField;
        
        private editorial editorialField;
        
        private System.DateTime fechaPublicacionField;
        
        private bool fechaPublicacionFieldSpecified;
        
        private int idLibroField;
        
        private ushort idiomaField;
        
        private int nroPaginasField;
        
        private byte[] portadaField;
        
        private double precioField;
        
        private string tituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("autores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public autor[] autores {
            get {
                return this.autoresField;
            }
            set {
                this.autoresField = value;
                this.RaisePropertyChanged("autores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public editorial editorial {
            get {
                return this.editorialField;
            }
            set {
                this.editorialField = value;
                this.RaisePropertyChanged("editorial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaPublicacion {
            get {
                return this.fechaPublicacionField;
            }
            set {
                this.fechaPublicacionField = value;
                this.RaisePropertyChanged("fechaPublicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaPublicacionSpecified {
            get {
                return this.fechaPublicacionFieldSpecified;
            }
            set {
                this.fechaPublicacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaPublicacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idLibro {
            get {
                return this.idLibroField;
            }
            set {
                this.idLibroField = value;
                this.RaisePropertyChanged("idLibro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public ushort idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
                this.RaisePropertyChanged("idioma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int nroPaginas {
            get {
                return this.nroPaginasField;
            }
            set {
                this.nroPaginasField = value;
                this.RaisePropertyChanged("nroPaginas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=7)]
        public byte[] portada {
            get {
                return this.portadaField;
            }
            set {
                this.portadaField = value;
                this.RaisePropertyChanged("portada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEditorialPorNombre", WrapperNamespace="http://services.rinconlibrosoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEditorialPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rinconlibrosoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarEditorialPorNombreRequest() {
        }
        
        public listarEditorialPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEditorialPorNombreResponse", WrapperNamespace="http://services.rinconlibrosoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEditorialPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rinconlibrosoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RinconLibroSoft.ServiciosWS.editorial[] @return;
        
        public listarEditorialPorNombreResponse() {
        }
        
        public listarEditorialPorNombreResponse(RinconLibroSoft.ServiciosWS.editorial[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarLibrosPorTituloOEditorial", WrapperNamespace="http://services.rinconlibrosoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarLibrosPorTituloOEditorialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rinconlibrosoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tituloOEditorial;
        
        public listarLibrosPorTituloOEditorialRequest() {
        }
        
        public listarLibrosPorTituloOEditorialRequest(string tituloOEditorial) {
            this.tituloOEditorial = tituloOEditorial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarLibrosPorTituloOEditorialResponse", WrapperNamespace="http://services.rinconlibrosoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarLibrosPorTituloOEditorialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rinconlibrosoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RinconLibroSoft.ServiciosWS.libro[] @return;
        
        public listarLibrosPorTituloOEditorialResponse() {
        }
        
        public listarLibrosPorTituloOEditorialResponse(RinconLibroSoft.ServiciosWS.libro[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAutoresPorIdLibro", WrapperNamespace="http://services.rinconlibrosoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAutoresPorIdLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rinconlibrosoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idLibro;
        
        public listarAutoresPorIdLibroRequest() {
        }
        
        public listarAutoresPorIdLibroRequest(int idLibro) {
            this.idLibro = idLibro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAutoresPorIdLibroResponse", WrapperNamespace="http://services.rinconlibrosoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAutoresPorIdLibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rinconlibrosoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RinconLibroSoft.ServiciosWS.autor[] @return;
        
        public listarAutoresPorIdLibroResponse() {
        }
        
        public listarAutoresPorIdLibroResponse(RinconLibroSoft.ServiciosWS.autor[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAutoresPorNombre", WrapperNamespace="http://services.rinconlibrosoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAutoresPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rinconlibrosoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarAutoresPorNombreRequest() {
        }
        
        public listarAutoresPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAutoresPorNombreResponse", WrapperNamespace="http://services.rinconlibrosoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAutoresPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rinconlibrosoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RinconLibroSoft.ServiciosWS.autor[] @return;
        
        public listarAutoresPorNombreResponse() {
        }
        
        public listarAutoresPorNombreResponse(RinconLibroSoft.ServiciosWS.autor[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://services.rinconlibrosoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rinconlibrosoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://services.rinconlibrosoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rinconlibrosoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarLibro", WrapperNamespace="http://services.rinconlibrosoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rinconlibrosoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RinconLibroSoft.ServiciosWS.libro libro;
        
        public insertarLibroRequest() {
        }
        
        public insertarLibroRequest(RinconLibroSoft.ServiciosWS.libro libro) {
            this.libro = libro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarLibroResponse", WrapperNamespace="http://services.rinconlibrosoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarLibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.rinconlibrosoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarLibroResponse() {
        }
        
        public insertarLibroResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosWSChannel : RinconLibroSoft.ServiciosWS.ServiciosWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosWSClient : System.ServiceModel.ClientBase<RinconLibroSoft.ServiciosWS.ServiciosWS>, RinconLibroSoft.ServiciosWS.ServiciosWS {
        
        public ServiciosWSClient() {
        }
        
        public ServiciosWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RinconLibroSoft.ServiciosWS.listarEditorialPorNombreResponse RinconLibroSoft.ServiciosWS.ServiciosWS.listarEditorialPorNombre(RinconLibroSoft.ServiciosWS.listarEditorialPorNombreRequest request) {
            return base.Channel.listarEditorialPorNombre(request);
        }
        
        public RinconLibroSoft.ServiciosWS.editorial[] listarEditorialPorNombre(string nombre) {
            RinconLibroSoft.ServiciosWS.listarEditorialPorNombreRequest inValue = new RinconLibroSoft.ServiciosWS.listarEditorialPorNombreRequest();
            inValue.nombre = nombre;
            RinconLibroSoft.ServiciosWS.listarEditorialPorNombreResponse retVal = ((RinconLibroSoft.ServiciosWS.ServiciosWS)(this)).listarEditorialPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RinconLibroSoft.ServiciosWS.listarEditorialPorNombreResponse> RinconLibroSoft.ServiciosWS.ServiciosWS.listarEditorialPorNombreAsync(RinconLibroSoft.ServiciosWS.listarEditorialPorNombreRequest request) {
            return base.Channel.listarEditorialPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<RinconLibroSoft.ServiciosWS.listarEditorialPorNombreResponse> listarEditorialPorNombreAsync(string nombre) {
            RinconLibroSoft.ServiciosWS.listarEditorialPorNombreRequest inValue = new RinconLibroSoft.ServiciosWS.listarEditorialPorNombreRequest();
            inValue.nombre = nombre;
            return ((RinconLibroSoft.ServiciosWS.ServiciosWS)(this)).listarEditorialPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RinconLibroSoft.ServiciosWS.listarLibrosPorTituloOEditorialResponse RinconLibroSoft.ServiciosWS.ServiciosWS.listarLibrosPorTituloOEditorial(RinconLibroSoft.ServiciosWS.listarLibrosPorTituloOEditorialRequest request) {
            return base.Channel.listarLibrosPorTituloOEditorial(request);
        }
        
        public RinconLibroSoft.ServiciosWS.libro[] listarLibrosPorTituloOEditorial(string tituloOEditorial) {
            RinconLibroSoft.ServiciosWS.listarLibrosPorTituloOEditorialRequest inValue = new RinconLibroSoft.ServiciosWS.listarLibrosPorTituloOEditorialRequest();
            inValue.tituloOEditorial = tituloOEditorial;
            RinconLibroSoft.ServiciosWS.listarLibrosPorTituloOEditorialResponse retVal = ((RinconLibroSoft.ServiciosWS.ServiciosWS)(this)).listarLibrosPorTituloOEditorial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RinconLibroSoft.ServiciosWS.listarLibrosPorTituloOEditorialResponse> RinconLibroSoft.ServiciosWS.ServiciosWS.listarLibrosPorTituloOEditorialAsync(RinconLibroSoft.ServiciosWS.listarLibrosPorTituloOEditorialRequest request) {
            return base.Channel.listarLibrosPorTituloOEditorialAsync(request);
        }
        
        public System.Threading.Tasks.Task<RinconLibroSoft.ServiciosWS.listarLibrosPorTituloOEditorialResponse> listarLibrosPorTituloOEditorialAsync(string tituloOEditorial) {
            RinconLibroSoft.ServiciosWS.listarLibrosPorTituloOEditorialRequest inValue = new RinconLibroSoft.ServiciosWS.listarLibrosPorTituloOEditorialRequest();
            inValue.tituloOEditorial = tituloOEditorial;
            return ((RinconLibroSoft.ServiciosWS.ServiciosWS)(this)).listarLibrosPorTituloOEditorialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RinconLibroSoft.ServiciosWS.listarAutoresPorIdLibroResponse RinconLibroSoft.ServiciosWS.ServiciosWS.listarAutoresPorIdLibro(RinconLibroSoft.ServiciosWS.listarAutoresPorIdLibroRequest request) {
            return base.Channel.listarAutoresPorIdLibro(request);
        }
        
        public RinconLibroSoft.ServiciosWS.autor[] listarAutoresPorIdLibro(int idLibro) {
            RinconLibroSoft.ServiciosWS.listarAutoresPorIdLibroRequest inValue = new RinconLibroSoft.ServiciosWS.listarAutoresPorIdLibroRequest();
            inValue.idLibro = idLibro;
            RinconLibroSoft.ServiciosWS.listarAutoresPorIdLibroResponse retVal = ((RinconLibroSoft.ServiciosWS.ServiciosWS)(this)).listarAutoresPorIdLibro(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RinconLibroSoft.ServiciosWS.listarAutoresPorIdLibroResponse> RinconLibroSoft.ServiciosWS.ServiciosWS.listarAutoresPorIdLibroAsync(RinconLibroSoft.ServiciosWS.listarAutoresPorIdLibroRequest request) {
            return base.Channel.listarAutoresPorIdLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<RinconLibroSoft.ServiciosWS.listarAutoresPorIdLibroResponse> listarAutoresPorIdLibroAsync(int idLibro) {
            RinconLibroSoft.ServiciosWS.listarAutoresPorIdLibroRequest inValue = new RinconLibroSoft.ServiciosWS.listarAutoresPorIdLibroRequest();
            inValue.idLibro = idLibro;
            return ((RinconLibroSoft.ServiciosWS.ServiciosWS)(this)).listarAutoresPorIdLibroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RinconLibroSoft.ServiciosWS.listarAutoresPorNombreResponse RinconLibroSoft.ServiciosWS.ServiciosWS.listarAutoresPorNombre(RinconLibroSoft.ServiciosWS.listarAutoresPorNombreRequest request) {
            return base.Channel.listarAutoresPorNombre(request);
        }
        
        public RinconLibroSoft.ServiciosWS.autor[] listarAutoresPorNombre(string nombre) {
            RinconLibroSoft.ServiciosWS.listarAutoresPorNombreRequest inValue = new RinconLibroSoft.ServiciosWS.listarAutoresPorNombreRequest();
            inValue.nombre = nombre;
            RinconLibroSoft.ServiciosWS.listarAutoresPorNombreResponse retVal = ((RinconLibroSoft.ServiciosWS.ServiciosWS)(this)).listarAutoresPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RinconLibroSoft.ServiciosWS.listarAutoresPorNombreResponse> RinconLibroSoft.ServiciosWS.ServiciosWS.listarAutoresPorNombreAsync(RinconLibroSoft.ServiciosWS.listarAutoresPorNombreRequest request) {
            return base.Channel.listarAutoresPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<RinconLibroSoft.ServiciosWS.listarAutoresPorNombreResponse> listarAutoresPorNombreAsync(string nombre) {
            RinconLibroSoft.ServiciosWS.listarAutoresPorNombreRequest inValue = new RinconLibroSoft.ServiciosWS.listarAutoresPorNombreRequest();
            inValue.nombre = nombre;
            return ((RinconLibroSoft.ServiciosWS.ServiciosWS)(this)).listarAutoresPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RinconLibroSoft.ServiciosWS.helloResponse RinconLibroSoft.ServiciosWS.ServiciosWS.hello(RinconLibroSoft.ServiciosWS.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            RinconLibroSoft.ServiciosWS.helloRequest inValue = new RinconLibroSoft.ServiciosWS.helloRequest();
            inValue.name = name;
            RinconLibroSoft.ServiciosWS.helloResponse retVal = ((RinconLibroSoft.ServiciosWS.ServiciosWS)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RinconLibroSoft.ServiciosWS.helloResponse> RinconLibroSoft.ServiciosWS.ServiciosWS.helloAsync(RinconLibroSoft.ServiciosWS.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<RinconLibroSoft.ServiciosWS.helloResponse> helloAsync(string name) {
            RinconLibroSoft.ServiciosWS.helloRequest inValue = new RinconLibroSoft.ServiciosWS.helloRequest();
            inValue.name = name;
            return ((RinconLibroSoft.ServiciosWS.ServiciosWS)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RinconLibroSoft.ServiciosWS.insertarLibroResponse RinconLibroSoft.ServiciosWS.ServiciosWS.insertarLibro(RinconLibroSoft.ServiciosWS.insertarLibroRequest request) {
            return base.Channel.insertarLibro(request);
        }
        
        public int insertarLibro(RinconLibroSoft.ServiciosWS.libro libro) {
            RinconLibroSoft.ServiciosWS.insertarLibroRequest inValue = new RinconLibroSoft.ServiciosWS.insertarLibroRequest();
            inValue.libro = libro;
            RinconLibroSoft.ServiciosWS.insertarLibroResponse retVal = ((RinconLibroSoft.ServiciosWS.ServiciosWS)(this)).insertarLibro(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RinconLibroSoft.ServiciosWS.insertarLibroResponse> RinconLibroSoft.ServiciosWS.ServiciosWS.insertarLibroAsync(RinconLibroSoft.ServiciosWS.insertarLibroRequest request) {
            return base.Channel.insertarLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<RinconLibroSoft.ServiciosWS.insertarLibroResponse> insertarLibroAsync(RinconLibroSoft.ServiciosWS.libro libro) {
            RinconLibroSoft.ServiciosWS.insertarLibroRequest inValue = new RinconLibroSoft.ServiciosWS.insertarLibroRequest();
            inValue.libro = libro;
            return ((RinconLibroSoft.ServiciosWS.ServiciosWS)(this)).insertarLibroAsync(inValue);
        }
    }
}
