//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaSoftLP2.ServiciosWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.cinemasoft.pucp.edu.pe/", ConfigurationName="ServiciosWS.ServiciosWS")]
    public interface ServiciosWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.cinemasoft.pucp.edu.pe/ServiciosWS/insertarPeliculaRequest", ReplyAction="http://webservices.cinemasoft.pucp.edu.pe/ServiciosWS/insertarPeliculaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CinemaSoftLP2.ServiciosWS.insertarPeliculaResponse insertarPelicula(CinemaSoftLP2.ServiciosWS.insertarPeliculaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.cinemasoft.pucp.edu.pe/ServiciosWS/insertarPeliculaRequest", ReplyAction="http://webservices.cinemasoft.pucp.edu.pe/ServiciosWS/insertarPeliculaResponse")]
        System.Threading.Tasks.Task<CinemaSoftLP2.ServiciosWS.insertarPeliculaResponse> insertarPeliculaAsync(CinemaSoftLP2.ServiciosWS.insertarPeliculaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.cinemasoft.pucp.edu.pe/ServiciosWS/listarActoresPorNombreReque" +
            "st", ReplyAction="http://webservices.cinemasoft.pucp.edu.pe/ServiciosWS/listarActoresPorNombreRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CinemaSoftLP2.ServiciosWS.listarActoresPorNombreResponse listarActoresPorNombre(CinemaSoftLP2.ServiciosWS.listarActoresPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.cinemasoft.pucp.edu.pe/ServiciosWS/listarActoresPorNombreReque" +
            "st", ReplyAction="http://webservices.cinemasoft.pucp.edu.pe/ServiciosWS/listarActoresPorNombreRespo" +
            "nse")]
        System.Threading.Tasks.Task<CinemaSoftLP2.ServiciosWS.listarActoresPorNombreResponse> listarActoresPorNombreAsync(CinemaSoftLP2.ServiciosWS.listarActoresPorNombreRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.cinemasoft.pucp.edu.pe/ServiciosWS/listarPeliculasPorTituloReq" +
            "uest", ReplyAction="http://webservices.cinemasoft.pucp.edu.pe/ServiciosWS/listarPeliculasPorTituloRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CinemaSoftLP2.ServiciosWS.listarPeliculasPorTituloResponse listarPeliculasPorTitulo(CinemaSoftLP2.ServiciosWS.listarPeliculasPorTituloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.cinemasoft.pucp.edu.pe/ServiciosWS/listarPeliculasPorTituloReq" +
            "uest", ReplyAction="http://webservices.cinemasoft.pucp.edu.pe/ServiciosWS/listarPeliculasPorTituloRes" +
            "ponse")]
        System.Threading.Tasks.Task<CinemaSoftLP2.ServiciosWS.listarPeliculasPorTituloResponse> listarPeliculasPorTituloAsync(CinemaSoftLP2.ServiciosWS.listarPeliculasPorTituloRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.cinemasoft.pucp.edu.pe/ServiciosWS/listarActoresPorIdPeliculaR" +
            "equest", ReplyAction="http://webservices.cinemasoft.pucp.edu.pe/ServiciosWS/listarActoresPorIdPeliculaR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CinemaSoftLP2.ServiciosWS.listarActoresPorIdPeliculaResponse listarActoresPorIdPelicula(CinemaSoftLP2.ServiciosWS.listarActoresPorIdPeliculaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.cinemasoft.pucp.edu.pe/ServiciosWS/listarActoresPorIdPeliculaR" +
            "equest", ReplyAction="http://webservices.cinemasoft.pucp.edu.pe/ServiciosWS/listarActoresPorIdPeliculaR" +
            "esponse")]
        System.Threading.Tasks.Task<CinemaSoftLP2.ServiciosWS.listarActoresPorIdPeliculaResponse> listarActoresPorIdPeliculaAsync(CinemaSoftLP2.ServiciosWS.listarActoresPorIdPeliculaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.cinemasoft.pucp.edu.pe/ServiciosWS/listarGenerosTodosRequest", ReplyAction="http://webservices.cinemasoft.pucp.edu.pe/ServiciosWS/listarGenerosTodosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CinemaSoftLP2.ServiciosWS.listarGenerosTodosResponse listarGenerosTodos(CinemaSoftLP2.ServiciosWS.listarGenerosTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.cinemasoft.pucp.edu.pe/ServiciosWS/listarGenerosTodosRequest", ReplyAction="http://webservices.cinemasoft.pucp.edu.pe/ServiciosWS/listarGenerosTodosResponse")]
        System.Threading.Tasks.Task<CinemaSoftLP2.ServiciosWS.listarGenerosTodosResponse> listarGenerosTodosAsync(CinemaSoftLP2.ServiciosWS.listarGenerosTodosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.cinemasoft.pucp.edu.pe/")]
    public partial class pelicula : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private actor[] actoresField;
        
        private bool disponibleDobladaField;
        
        private bool disponibleSubtituladaField;
        
        private string duracionField;
        
        private System.DateTime fechaEstrenoField;
        
        private bool fechaEstrenoFieldSpecified;
        
        private genero generoField;
        
        private int idPeliculaField;
        
        private byte[] portadaField;
        
        private string sinopsisField;
        
        private string tituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("actores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public actor[] actores {
            get {
                return this.actoresField;
            }
            set {
                this.actoresField = value;
                this.RaisePropertyChanged("actores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool disponibleDoblada {
            get {
                return this.disponibleDobladaField;
            }
            set {
                this.disponibleDobladaField = value;
                this.RaisePropertyChanged("disponibleDoblada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool disponibleSubtitulada {
            get {
                return this.disponibleSubtituladaField;
            }
            set {
                this.disponibleSubtituladaField = value;
                this.RaisePropertyChanged("disponibleSubtitulada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string duracion {
            get {
                return this.duracionField;
            }
            set {
                this.duracionField = value;
                this.RaisePropertyChanged("duracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaEstreno {
            get {
                return this.fechaEstrenoField;
            }
            set {
                this.fechaEstrenoField = value;
                this.RaisePropertyChanged("fechaEstreno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEstrenoSpecified {
            get {
                return this.fechaEstrenoFieldSpecified;
            }
            set {
                this.fechaEstrenoFieldSpecified = value;
                this.RaisePropertyChanged("fechaEstrenoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public genero genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int idPelicula {
            get {
                return this.idPeliculaField;
            }
            set {
                this.idPeliculaField = value;
                this.RaisePropertyChanged("idPelicula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=8)]
        public byte[] portada {
            get {
                return this.portadaField;
            }
            set {
                this.portadaField = value;
                this.RaisePropertyChanged("portada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string sinopsis {
            get {
                return this.sinopsisField;
            }
            set {
                this.sinopsisField = value;
                this.RaisePropertyChanged("sinopsis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.cinemasoft.pucp.edu.pe/")]
    public partial class actor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string apellidoPaternoField;
        
        private int idActorField;
        
        private string nacionalidadField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idActor {
            get {
                return this.idActorField;
            }
            set {
                this.idActorField = value;
                this.RaisePropertyChanged("idActor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
                this.RaisePropertyChanged("nacionalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.cinemasoft.pucp.edu.pe/")]
    public partial class genero : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idGeneroField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idGenero {
            get {
                return this.idGeneroField;
            }
            set {
                this.idGeneroField = value;
                this.RaisePropertyChanged("idGenero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPelicula", WrapperNamespace="http://webservices.cinemasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPeliculaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.cinemasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CinemaSoftLP2.ServiciosWS.pelicula pelicula;
        
        public insertarPeliculaRequest() {
        }
        
        public insertarPeliculaRequest(CinemaSoftLP2.ServiciosWS.pelicula pelicula) {
            this.pelicula = pelicula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPeliculaResponse", WrapperNamespace="http://webservices.cinemasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPeliculaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.cinemasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPeliculaResponse() {
        }
        
        public insertarPeliculaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarActoresPorNombre", WrapperNamespace="http://webservices.cinemasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarActoresPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.cinemasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarActoresPorNombreRequest() {
        }
        
        public listarActoresPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarActoresPorNombreResponse", WrapperNamespace="http://webservices.cinemasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarActoresPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.cinemasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CinemaSoftLP2.ServiciosWS.actor[] @return;
        
        public listarActoresPorNombreResponse() {
        }
        
        public listarActoresPorNombreResponse(CinemaSoftLP2.ServiciosWS.actor[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPeliculasPorTitulo", WrapperNamespace="http://webservices.cinemasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPeliculasPorTituloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.cinemasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pelicula;
        
        public listarPeliculasPorTituloRequest() {
        }
        
        public listarPeliculasPorTituloRequest(string pelicula) {
            this.pelicula = pelicula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPeliculasPorTituloResponse", WrapperNamespace="http://webservices.cinemasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPeliculasPorTituloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.cinemasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CinemaSoftLP2.ServiciosWS.pelicula[] @return;
        
        public listarPeliculasPorTituloResponse() {
        }
        
        public listarPeliculasPorTituloResponse(CinemaSoftLP2.ServiciosWS.pelicula[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarActoresPorIdPelicula", WrapperNamespace="http://webservices.cinemasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarActoresPorIdPeliculaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.cinemasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPelicula;
        
        public listarActoresPorIdPeliculaRequest() {
        }
        
        public listarActoresPorIdPeliculaRequest(int idPelicula) {
            this.idPelicula = idPelicula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarActoresPorIdPeliculaResponse", WrapperNamespace="http://webservices.cinemasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarActoresPorIdPeliculaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.cinemasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CinemaSoftLP2.ServiciosWS.actor[] @return;
        
        public listarActoresPorIdPeliculaResponse() {
        }
        
        public listarActoresPorIdPeliculaResponse(CinemaSoftLP2.ServiciosWS.actor[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarGenerosTodos", WrapperNamespace="http://webservices.cinemasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarGenerosTodosRequest {
        
        public listarGenerosTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarGenerosTodosResponse", WrapperNamespace="http://webservices.cinemasoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarGenerosTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.cinemasoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CinemaSoftLP2.ServiciosWS.genero[] @return;
        
        public listarGenerosTodosResponse() {
        }
        
        public listarGenerosTodosResponse(CinemaSoftLP2.ServiciosWS.genero[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosWSChannel : CinemaSoftLP2.ServiciosWS.ServiciosWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosWSClient : System.ServiceModel.ClientBase<CinemaSoftLP2.ServiciosWS.ServiciosWS>, CinemaSoftLP2.ServiciosWS.ServiciosWS {
        
        public ServiciosWSClient() {
        }
        
        public ServiciosWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CinemaSoftLP2.ServiciosWS.insertarPeliculaResponse CinemaSoftLP2.ServiciosWS.ServiciosWS.insertarPelicula(CinemaSoftLP2.ServiciosWS.insertarPeliculaRequest request) {
            return base.Channel.insertarPelicula(request);
        }
        
        public int insertarPelicula(CinemaSoftLP2.ServiciosWS.pelicula pelicula) {
            CinemaSoftLP2.ServiciosWS.insertarPeliculaRequest inValue = new CinemaSoftLP2.ServiciosWS.insertarPeliculaRequest();
            inValue.pelicula = pelicula;
            CinemaSoftLP2.ServiciosWS.insertarPeliculaResponse retVal = ((CinemaSoftLP2.ServiciosWS.ServiciosWS)(this)).insertarPelicula(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CinemaSoftLP2.ServiciosWS.insertarPeliculaResponse> CinemaSoftLP2.ServiciosWS.ServiciosWS.insertarPeliculaAsync(CinemaSoftLP2.ServiciosWS.insertarPeliculaRequest request) {
            return base.Channel.insertarPeliculaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CinemaSoftLP2.ServiciosWS.insertarPeliculaResponse> insertarPeliculaAsync(CinemaSoftLP2.ServiciosWS.pelicula pelicula) {
            CinemaSoftLP2.ServiciosWS.insertarPeliculaRequest inValue = new CinemaSoftLP2.ServiciosWS.insertarPeliculaRequest();
            inValue.pelicula = pelicula;
            return ((CinemaSoftLP2.ServiciosWS.ServiciosWS)(this)).insertarPeliculaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CinemaSoftLP2.ServiciosWS.listarActoresPorNombreResponse CinemaSoftLP2.ServiciosWS.ServiciosWS.listarActoresPorNombre(CinemaSoftLP2.ServiciosWS.listarActoresPorNombreRequest request) {
            return base.Channel.listarActoresPorNombre(request);
        }
        
        public CinemaSoftLP2.ServiciosWS.actor[] listarActoresPorNombre(string nombre) {
            CinemaSoftLP2.ServiciosWS.listarActoresPorNombreRequest inValue = new CinemaSoftLP2.ServiciosWS.listarActoresPorNombreRequest();
            inValue.nombre = nombre;
            CinemaSoftLP2.ServiciosWS.listarActoresPorNombreResponse retVal = ((CinemaSoftLP2.ServiciosWS.ServiciosWS)(this)).listarActoresPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CinemaSoftLP2.ServiciosWS.listarActoresPorNombreResponse> CinemaSoftLP2.ServiciosWS.ServiciosWS.listarActoresPorNombreAsync(CinemaSoftLP2.ServiciosWS.listarActoresPorNombreRequest request) {
            return base.Channel.listarActoresPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<CinemaSoftLP2.ServiciosWS.listarActoresPorNombreResponse> listarActoresPorNombreAsync(string nombre) {
            CinemaSoftLP2.ServiciosWS.listarActoresPorNombreRequest inValue = new CinemaSoftLP2.ServiciosWS.listarActoresPorNombreRequest();
            inValue.nombre = nombre;
            return ((CinemaSoftLP2.ServiciosWS.ServiciosWS)(this)).listarActoresPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CinemaSoftLP2.ServiciosWS.listarPeliculasPorTituloResponse CinemaSoftLP2.ServiciosWS.ServiciosWS.listarPeliculasPorTitulo(CinemaSoftLP2.ServiciosWS.listarPeliculasPorTituloRequest request) {
            return base.Channel.listarPeliculasPorTitulo(request);
        }
        
        public CinemaSoftLP2.ServiciosWS.pelicula[] listarPeliculasPorTitulo(string pelicula) {
            CinemaSoftLP2.ServiciosWS.listarPeliculasPorTituloRequest inValue = new CinemaSoftLP2.ServiciosWS.listarPeliculasPorTituloRequest();
            inValue.pelicula = pelicula;
            CinemaSoftLP2.ServiciosWS.listarPeliculasPorTituloResponse retVal = ((CinemaSoftLP2.ServiciosWS.ServiciosWS)(this)).listarPeliculasPorTitulo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CinemaSoftLP2.ServiciosWS.listarPeliculasPorTituloResponse> CinemaSoftLP2.ServiciosWS.ServiciosWS.listarPeliculasPorTituloAsync(CinemaSoftLP2.ServiciosWS.listarPeliculasPorTituloRequest request) {
            return base.Channel.listarPeliculasPorTituloAsync(request);
        }
        
        public System.Threading.Tasks.Task<CinemaSoftLP2.ServiciosWS.listarPeliculasPorTituloResponse> listarPeliculasPorTituloAsync(string pelicula) {
            CinemaSoftLP2.ServiciosWS.listarPeliculasPorTituloRequest inValue = new CinemaSoftLP2.ServiciosWS.listarPeliculasPorTituloRequest();
            inValue.pelicula = pelicula;
            return ((CinemaSoftLP2.ServiciosWS.ServiciosWS)(this)).listarPeliculasPorTituloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CinemaSoftLP2.ServiciosWS.listarActoresPorIdPeliculaResponse CinemaSoftLP2.ServiciosWS.ServiciosWS.listarActoresPorIdPelicula(CinemaSoftLP2.ServiciosWS.listarActoresPorIdPeliculaRequest request) {
            return base.Channel.listarActoresPorIdPelicula(request);
        }
        
        public CinemaSoftLP2.ServiciosWS.actor[] listarActoresPorIdPelicula(int idPelicula) {
            CinemaSoftLP2.ServiciosWS.listarActoresPorIdPeliculaRequest inValue = new CinemaSoftLP2.ServiciosWS.listarActoresPorIdPeliculaRequest();
            inValue.idPelicula = idPelicula;
            CinemaSoftLP2.ServiciosWS.listarActoresPorIdPeliculaResponse retVal = ((CinemaSoftLP2.ServiciosWS.ServiciosWS)(this)).listarActoresPorIdPelicula(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CinemaSoftLP2.ServiciosWS.listarActoresPorIdPeliculaResponse> CinemaSoftLP2.ServiciosWS.ServiciosWS.listarActoresPorIdPeliculaAsync(CinemaSoftLP2.ServiciosWS.listarActoresPorIdPeliculaRequest request) {
            return base.Channel.listarActoresPorIdPeliculaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CinemaSoftLP2.ServiciosWS.listarActoresPorIdPeliculaResponse> listarActoresPorIdPeliculaAsync(int idPelicula) {
            CinemaSoftLP2.ServiciosWS.listarActoresPorIdPeliculaRequest inValue = new CinemaSoftLP2.ServiciosWS.listarActoresPorIdPeliculaRequest();
            inValue.idPelicula = idPelicula;
            return ((CinemaSoftLP2.ServiciosWS.ServiciosWS)(this)).listarActoresPorIdPeliculaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CinemaSoftLP2.ServiciosWS.listarGenerosTodosResponse CinemaSoftLP2.ServiciosWS.ServiciosWS.listarGenerosTodos(CinemaSoftLP2.ServiciosWS.listarGenerosTodosRequest request) {
            return base.Channel.listarGenerosTodos(request);
        }
        
        public CinemaSoftLP2.ServiciosWS.genero[] listarGenerosTodos() {
            CinemaSoftLP2.ServiciosWS.listarGenerosTodosRequest inValue = new CinemaSoftLP2.ServiciosWS.listarGenerosTodosRequest();
            CinemaSoftLP2.ServiciosWS.listarGenerosTodosResponse retVal = ((CinemaSoftLP2.ServiciosWS.ServiciosWS)(this)).listarGenerosTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CinemaSoftLP2.ServiciosWS.listarGenerosTodosResponse> CinemaSoftLP2.ServiciosWS.ServiciosWS.listarGenerosTodosAsync(CinemaSoftLP2.ServiciosWS.listarGenerosTodosRequest request) {
            return base.Channel.listarGenerosTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<CinemaSoftLP2.ServiciosWS.listarGenerosTodosResponse> listarGenerosTodosAsync() {
            CinemaSoftLP2.ServiciosWS.listarGenerosTodosRequest inValue = new CinemaSoftLP2.ServiciosWS.listarGenerosTodosRequest();
            return ((CinemaSoftLP2.ServiciosWS.ServiciosWS)(this)).listarGenerosTodosAsync(inValue);
        }
    }
}
