//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngeSoftVirtual.ServicioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.ingesoft.pucp.edu.pe/", ConfigurationName="ServicioWS.ServiciosWS")]
    public interface ServiciosWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.ingesoft.pucp.edu.pe/ServiciosWS/listarEspecialidadesTodasRequ" +
            "est", ReplyAction="http://webservices.ingesoft.pucp.edu.pe/ServiciosWS/listarEspecialidadesTodasResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IngeSoftVirtual.ServicioWS.listarEspecialidadesTodasResponse listarEspecialidadesTodas(IngeSoftVirtual.ServicioWS.listarEspecialidadesTodasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.ingesoft.pucp.edu.pe/ServiciosWS/listarEspecialidadesTodasRequ" +
            "est", ReplyAction="http://webservices.ingesoft.pucp.edu.pe/ServiciosWS/listarEspecialidadesTodasResp" +
            "onse")]
        System.Threading.Tasks.Task<IngeSoftVirtual.ServicioWS.listarEspecialidadesTodasResponse> listarEspecialidadesTodasAsync(IngeSoftVirtual.ServicioWS.listarEspecialidadesTodasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.ingesoft.pucp.edu.pe/ServiciosWS/listarCursosPorNombreRequest", ReplyAction="http://webservices.ingesoft.pucp.edu.pe/ServiciosWS/listarCursosPorNombreResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IngeSoftVirtual.ServicioWS.listarCursosPorNombreResponse listarCursosPorNombre(IngeSoftVirtual.ServicioWS.listarCursosPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.ingesoft.pucp.edu.pe/ServiciosWS/listarCursosPorNombreRequest", ReplyAction="http://webservices.ingesoft.pucp.edu.pe/ServiciosWS/listarCursosPorNombreResponse" +
            "")]
        System.Threading.Tasks.Task<IngeSoftVirtual.ServicioWS.listarCursosPorNombreResponse> listarCursosPorNombreAsync(IngeSoftVirtual.ServicioWS.listarCursosPorNombreRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.ingesoft.pucp.edu.pe/ServiciosWS/insertarCursoRequest", ReplyAction="http://webservices.ingesoft.pucp.edu.pe/ServiciosWS/insertarCursoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        IngeSoftVirtual.ServicioWS.insertarCursoResponse insertarCurso(IngeSoftVirtual.ServicioWS.insertarCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.ingesoft.pucp.edu.pe/ServiciosWS/insertarCursoRequest", ReplyAction="http://webservices.ingesoft.pucp.edu.pe/ServiciosWS/insertarCursoResponse")]
        System.Threading.Tasks.Task<IngeSoftVirtual.ServicioWS.insertarCursoResponse> insertarCursoAsync(IngeSoftVirtual.ServicioWS.insertarCursoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.ingesoft.pucp.edu.pe/")]
    public partial class especialidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idEspecialidadField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idEspecialidad {
            get {
                return this.idEspecialidadField;
            }
            set {
                this.idEspecialidadField = value;
                this.RaisePropertyChanged("idEspecialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.ingesoft.pucp.edu.pe/")]
    public partial class curso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string claveField;
        
        private int creditosField;
        
        private especialidad especialidadField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idCursoField;
        
        private string nombreField;
        
        private double precioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int creditos {
            get {
                return this.creditosField;
            }
            set {
                this.creditosField = value;
                this.RaisePropertyChanged("creditos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public especialidad especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idCurso {
            get {
                return this.idCursoField;
            }
            set {
                this.idCursoField = value;
                this.RaisePropertyChanged("idCurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEspecialidadesTodas", WrapperNamespace="http://webservices.ingesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEspecialidadesTodasRequest {
        
        public listarEspecialidadesTodasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEspecialidadesTodasResponse", WrapperNamespace="http://webservices.ingesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEspecialidadesTodasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.ingesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IngeSoftVirtual.ServicioWS.especialidad[] @return;
        
        public listarEspecialidadesTodasResponse() {
        }
        
        public listarEspecialidadesTodasResponse(IngeSoftVirtual.ServicioWS.especialidad[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCursosPorNombre", WrapperNamespace="http://webservices.ingesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCursosPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.ingesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarCursosPorNombreRequest() {
        }
        
        public listarCursosPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCursosPorNombreResponse", WrapperNamespace="http://webservices.ingesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCursosPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.ingesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IngeSoftVirtual.ServicioWS.curso[] @return;
        
        public listarCursosPorNombreResponse() {
        }
        
        public listarCursosPorNombreResponse(IngeSoftVirtual.ServicioWS.curso[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCurso", WrapperNamespace="http://webservices.ingesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCursoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.ingesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public IngeSoftVirtual.ServicioWS.curso curso;
        
        public insertarCursoRequest() {
        }
        
        public insertarCursoRequest(IngeSoftVirtual.ServicioWS.curso curso) {
            this.curso = curso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCursoResponse", WrapperNamespace="http://webservices.ingesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCursoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.ingesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarCursoResponse() {
        }
        
        public insertarCursoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosWSChannel : IngeSoftVirtual.ServicioWS.ServiciosWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosWSClient : System.ServiceModel.ClientBase<IngeSoftVirtual.ServicioWS.ServiciosWS>, IngeSoftVirtual.ServicioWS.ServiciosWS {
        
        public ServiciosWSClient() {
        }
        
        public ServiciosWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IngeSoftVirtual.ServicioWS.listarEspecialidadesTodasResponse IngeSoftVirtual.ServicioWS.ServiciosWS.listarEspecialidadesTodas(IngeSoftVirtual.ServicioWS.listarEspecialidadesTodasRequest request) {
            return base.Channel.listarEspecialidadesTodas(request);
        }
        
        public IngeSoftVirtual.ServicioWS.especialidad[] listarEspecialidadesTodas() {
            IngeSoftVirtual.ServicioWS.listarEspecialidadesTodasRequest inValue = new IngeSoftVirtual.ServicioWS.listarEspecialidadesTodasRequest();
            IngeSoftVirtual.ServicioWS.listarEspecialidadesTodasResponse retVal = ((IngeSoftVirtual.ServicioWS.ServiciosWS)(this)).listarEspecialidadesTodas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IngeSoftVirtual.ServicioWS.listarEspecialidadesTodasResponse> IngeSoftVirtual.ServicioWS.ServiciosWS.listarEspecialidadesTodasAsync(IngeSoftVirtual.ServicioWS.listarEspecialidadesTodasRequest request) {
            return base.Channel.listarEspecialidadesTodasAsync(request);
        }
        
        public System.Threading.Tasks.Task<IngeSoftVirtual.ServicioWS.listarEspecialidadesTodasResponse> listarEspecialidadesTodasAsync() {
            IngeSoftVirtual.ServicioWS.listarEspecialidadesTodasRequest inValue = new IngeSoftVirtual.ServicioWS.listarEspecialidadesTodasRequest();
            return ((IngeSoftVirtual.ServicioWS.ServiciosWS)(this)).listarEspecialidadesTodasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IngeSoftVirtual.ServicioWS.listarCursosPorNombreResponse IngeSoftVirtual.ServicioWS.ServiciosWS.listarCursosPorNombre(IngeSoftVirtual.ServicioWS.listarCursosPorNombreRequest request) {
            return base.Channel.listarCursosPorNombre(request);
        }
        
        public IngeSoftVirtual.ServicioWS.curso[] listarCursosPorNombre(string nombre) {
            IngeSoftVirtual.ServicioWS.listarCursosPorNombreRequest inValue = new IngeSoftVirtual.ServicioWS.listarCursosPorNombreRequest();
            inValue.nombre = nombre;
            IngeSoftVirtual.ServicioWS.listarCursosPorNombreResponse retVal = ((IngeSoftVirtual.ServicioWS.ServiciosWS)(this)).listarCursosPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IngeSoftVirtual.ServicioWS.listarCursosPorNombreResponse> IngeSoftVirtual.ServicioWS.ServiciosWS.listarCursosPorNombreAsync(IngeSoftVirtual.ServicioWS.listarCursosPorNombreRequest request) {
            return base.Channel.listarCursosPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<IngeSoftVirtual.ServicioWS.listarCursosPorNombreResponse> listarCursosPorNombreAsync(string nombre) {
            IngeSoftVirtual.ServicioWS.listarCursosPorNombreRequest inValue = new IngeSoftVirtual.ServicioWS.listarCursosPorNombreRequest();
            inValue.nombre = nombre;
            return ((IngeSoftVirtual.ServicioWS.ServiciosWS)(this)).listarCursosPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IngeSoftVirtual.ServicioWS.insertarCursoResponse IngeSoftVirtual.ServicioWS.ServiciosWS.insertarCurso(IngeSoftVirtual.ServicioWS.insertarCursoRequest request) {
            return base.Channel.insertarCurso(request);
        }
        
        public int insertarCurso(IngeSoftVirtual.ServicioWS.curso curso) {
            IngeSoftVirtual.ServicioWS.insertarCursoRequest inValue = new IngeSoftVirtual.ServicioWS.insertarCursoRequest();
            inValue.curso = curso;
            IngeSoftVirtual.ServicioWS.insertarCursoResponse retVal = ((IngeSoftVirtual.ServicioWS.ServiciosWS)(this)).insertarCurso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IngeSoftVirtual.ServicioWS.insertarCursoResponse> IngeSoftVirtual.ServicioWS.ServiciosWS.insertarCursoAsync(IngeSoftVirtual.ServicioWS.insertarCursoRequest request) {
            return base.Channel.insertarCursoAsync(request);
        }
        
        public System.Threading.Tasks.Task<IngeSoftVirtual.ServicioWS.insertarCursoResponse> insertarCursoAsync(IngeSoftVirtual.ServicioWS.curso curso) {
            IngeSoftVirtual.ServicioWS.insertarCursoRequest inValue = new IngeSoftVirtual.ServicioWS.insertarCursoRequest();
            inValue.curso = curso;
            return ((IngeSoftVirtual.ServicioWS.ServiciosWS)(this)).insertarCursoAsync(inValue);
        }
    }
}
