//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSoft.ServiciosWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.eventsoft.pucp.edu.pe/", ConfigurationName="ServiciosWS.ServiciosWS")]
    public interface ServiciosWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/listarDocentesPorCodigoPUCPN" +
            "ombreIdEspecialidadRequest", ReplyAction="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/listarDocentesPorCodigoPUCPN" +
            "ombreIdEspecialidadResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EventSoft.ServiciosWS.listarDocentesPorCodigoPUCPNombreIdEspecialidadResponse listarDocentesPorCodigoPUCPNombreIdEspecialidad(EventSoft.ServiciosWS.listarDocentesPorCodigoPUCPNombreIdEspecialidadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/listarDocentesPorCodigoPUCPN" +
            "ombreIdEspecialidadRequest", ReplyAction="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/listarDocentesPorCodigoPUCPN" +
            "ombreIdEspecialidadResponse")]
        System.Threading.Tasks.Task<EventSoft.ServiciosWS.listarDocentesPorCodigoPUCPNombreIdEspecialidadResponse> listarDocentesPorCodigoPUCPNombreIdEspecialidadAsync(EventSoft.ServiciosWS.listarDocentesPorCodigoPUCPNombreIdEspecialidadRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/listarEspecialidadesTodasReq" +
            "uest", ReplyAction="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/listarEspecialidadesTodasRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EventSoft.ServiciosWS.listarEspecialidadesTodasResponse listarEspecialidadesTodas(EventSoft.ServiciosWS.listarEspecialidadesTodasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/listarEspecialidadesTodasReq" +
            "uest", ReplyAction="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/listarEspecialidadesTodasRes" +
            "ponse")]
        System.Threading.Tasks.Task<EventSoft.ServiciosWS.listarEspecialidadesTodasResponse> listarEspecialidadesTodasAsync(EventSoft.ServiciosWS.listarEspecialidadesTodasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/listarDocentePorIdEventoRequ" +
            "est", ReplyAction="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/listarDocentePorIdEventoResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EventSoft.ServiciosWS.listarDocentePorIdEventoResponse listarDocentePorIdEvento(EventSoft.ServiciosWS.listarDocentePorIdEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/listarDocentePorIdEventoRequ" +
            "est", ReplyAction="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/listarDocentePorIdEventoResp" +
            "onse")]
        System.Threading.Tasks.Task<EventSoft.ServiciosWS.listarDocentePorIdEventoResponse> listarDocentePorIdEventoAsync(EventSoft.ServiciosWS.listarDocentePorIdEventoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/listarActividadesPorIdEvento" +
            "Request", ReplyAction="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/listarActividadesPorIdEvento" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EventSoft.ServiciosWS.listarActividadesPorIdEventoResponse listarActividadesPorIdEvento(EventSoft.ServiciosWS.listarActividadesPorIdEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/listarActividadesPorIdEvento" +
            "Request", ReplyAction="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/listarActividadesPorIdEvento" +
            "Response")]
        System.Threading.Tasks.Task<EventSoft.ServiciosWS.listarActividadesPorIdEventoResponse> listarActividadesPorIdEventoAsync(EventSoft.ServiciosWS.listarActividadesPorIdEventoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/listarEventosPorNombreReques" +
            "t", ReplyAction="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/listarEventosPorNombreRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EventSoft.ServiciosWS.listarEventosPorNombreResponse listarEventosPorNombre(EventSoft.ServiciosWS.listarEventosPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/listarEventosPorNombreReques" +
            "t", ReplyAction="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/listarEventosPorNombreRespon" +
            "se")]
        System.Threading.Tasks.Task<EventSoft.ServiciosWS.listarEventosPorNombreResponse> listarEventosPorNombreAsync(EventSoft.ServiciosWS.listarEventosPorNombreRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/insertarEventoRequest", ReplyAction="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/insertarEventoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EventSoft.ServiciosWS.insertarEventoResponse insertarEvento(EventSoft.ServiciosWS.insertarEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/insertarEventoRequest", ReplyAction="http://webservices.eventsoft.pucp.edu.pe/ServiciosWS/insertarEventoResponse")]
        System.Threading.Tasks.Task<EventSoft.ServiciosWS.insertarEventoResponse> insertarEventoAsync(EventSoft.ServiciosWS.insertarEventoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.eventsoft.pucp.edu.pe/")]
    public partial class docente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string codigoPUCPField;
        
        private especialidad especialidadField;
        
        private int idDocenteField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string codigoPUCP {
            get {
                return this.codigoPUCPField;
            }
            set {
                this.codigoPUCPField = value;
                this.RaisePropertyChanged("codigoPUCP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public especialidad especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idDocente {
            get {
                return this.idDocenteField;
            }
            set {
                this.idDocenteField = value;
                this.RaisePropertyChanged("idDocente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.eventsoft.pucp.edu.pe/")]
    public partial class especialidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activaField;
        
        private int idEspecialidadField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idEspecialidad {
            get {
                return this.idEspecialidadField;
            }
            set {
                this.idEspecialidadField = value;
                this.RaisePropertyChanged("idEspecialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.eventsoft.pucp.edu.pe/")]
    public partial class evento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private actividad[] actividadesField;
        
        private bool activoField;
        
        private double costoField;
        
        private especialidad especialidadField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private byte[] fotoField;
        
        private int idEventoField;
        
        private string nombreField;
        
        private docente[] responsablesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("actividades", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public actividad[] actividades {
            get {
                return this.actividadesField;
            }
            set {
                this.actividadesField = value;
                this.RaisePropertyChanged("actividades");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double costo {
            get {
                return this.costoField;
            }
            set {
                this.costoField = value;
                this.RaisePropertyChanged("costo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public especialidad especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=6)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int idEvento {
            get {
                return this.idEventoField;
            }
            set {
                this.idEventoField = value;
                this.RaisePropertyChanged("idEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("responsables", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public docente[] responsables {
            get {
                return this.responsablesField;
            }
            set {
                this.responsablesField = value;
                this.RaisePropertyChanged("responsables");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.eventsoft.pucp.edu.pe/")]
    public partial class actividad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activaField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private string horaFinField;
        
        private string horaInicioField;
        
        private int idActividadField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string horaFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
                this.RaisePropertyChanged("horaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string horaInicio {
            get {
                return this.horaInicioField;
            }
            set {
                this.horaInicioField = value;
                this.RaisePropertyChanged("horaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idActividad {
            get {
                return this.idActividadField;
            }
            set {
                this.idActividadField = value;
                this.RaisePropertyChanged("idActividad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDocentesPorCodigoPUCPNombreIdEspecialidad", WrapperNamespace="http://webservices.eventsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDocentesPorCodigoPUCPNombreIdEspecialidadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.eventsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.eventsoft.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEspecialidad;
        
        public listarDocentesPorCodigoPUCPNombreIdEspecialidadRequest() {
        }
        
        public listarDocentesPorCodigoPUCPNombreIdEspecialidadRequest(string nombre, int idEspecialidad) {
            this.nombre = nombre;
            this.idEspecialidad = idEspecialidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDocentesPorCodigoPUCPNombreIdEspecialidadResponse", WrapperNamespace="http://webservices.eventsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDocentesPorCodigoPUCPNombreIdEspecialidadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.eventsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EventSoft.ServiciosWS.docente[] @return;
        
        public listarDocentesPorCodigoPUCPNombreIdEspecialidadResponse() {
        }
        
        public listarDocentesPorCodigoPUCPNombreIdEspecialidadResponse(EventSoft.ServiciosWS.docente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEspecialidadesTodas", WrapperNamespace="http://webservices.eventsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEspecialidadesTodasRequest {
        
        public listarEspecialidadesTodasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEspecialidadesTodasResponse", WrapperNamespace="http://webservices.eventsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEspecialidadesTodasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.eventsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EventSoft.ServiciosWS.especialidad[] @return;
        
        public listarEspecialidadesTodasResponse() {
        }
        
        public listarEspecialidadesTodasResponse(EventSoft.ServiciosWS.especialidad[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDocentePorIdEvento", WrapperNamespace="http://webservices.eventsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDocentePorIdEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.eventsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEvento;
        
        public listarDocentePorIdEventoRequest() {
        }
        
        public listarDocentePorIdEventoRequest(int idEvento) {
            this.idEvento = idEvento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDocentePorIdEventoResponse", WrapperNamespace="http://webservices.eventsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDocentePorIdEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.eventsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EventSoft.ServiciosWS.docente[] @return;
        
        public listarDocentePorIdEventoResponse() {
        }
        
        public listarDocentePorIdEventoResponse(EventSoft.ServiciosWS.docente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarActividadesPorIdEvento", WrapperNamespace="http://webservices.eventsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarActividadesPorIdEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.eventsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEvento;
        
        public listarActividadesPorIdEventoRequest() {
        }
        
        public listarActividadesPorIdEventoRequest(int idEvento) {
            this.idEvento = idEvento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarActividadesPorIdEventoResponse", WrapperNamespace="http://webservices.eventsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarActividadesPorIdEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.eventsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EventSoft.ServiciosWS.actividad[] @return;
        
        public listarActividadesPorIdEventoResponse() {
        }
        
        public listarActividadesPorIdEventoResponse(EventSoft.ServiciosWS.actividad[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEventosPorNombre", WrapperNamespace="http://webservices.eventsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEventosPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.eventsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarEventosPorNombreRequest() {
        }
        
        public listarEventosPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEventosPorNombreResponse", WrapperNamespace="http://webservices.eventsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEventosPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.eventsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EventSoft.ServiciosWS.evento[] @return;
        
        public listarEventosPorNombreResponse() {
        }
        
        public listarEventosPorNombreResponse(EventSoft.ServiciosWS.evento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEvento", WrapperNamespace="http://webservices.eventsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.eventsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EventSoft.ServiciosWS.evento evento;
        
        public insertarEventoRequest() {
        }
        
        public insertarEventoRequest(EventSoft.ServiciosWS.evento evento) {
            this.evento = evento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEventoResponse", WrapperNamespace="http://webservices.eventsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.eventsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarEventoResponse() {
        }
        
        public insertarEventoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosWSChannel : EventSoft.ServiciosWS.ServiciosWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosWSClient : System.ServiceModel.ClientBase<EventSoft.ServiciosWS.ServiciosWS>, EventSoft.ServiciosWS.ServiciosWS {
        
        public ServiciosWSClient() {
        }
        
        public ServiciosWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EventSoft.ServiciosWS.listarDocentesPorCodigoPUCPNombreIdEspecialidadResponse EventSoft.ServiciosWS.ServiciosWS.listarDocentesPorCodigoPUCPNombreIdEspecialidad(EventSoft.ServiciosWS.listarDocentesPorCodigoPUCPNombreIdEspecialidadRequest request) {
            return base.Channel.listarDocentesPorCodigoPUCPNombreIdEspecialidad(request);
        }
        
        public EventSoft.ServiciosWS.docente[] listarDocentesPorCodigoPUCPNombreIdEspecialidad(string nombre, int idEspecialidad) {
            EventSoft.ServiciosWS.listarDocentesPorCodigoPUCPNombreIdEspecialidadRequest inValue = new EventSoft.ServiciosWS.listarDocentesPorCodigoPUCPNombreIdEspecialidadRequest();
            inValue.nombre = nombre;
            inValue.idEspecialidad = idEspecialidad;
            EventSoft.ServiciosWS.listarDocentesPorCodigoPUCPNombreIdEspecialidadResponse retVal = ((EventSoft.ServiciosWS.ServiciosWS)(this)).listarDocentesPorCodigoPUCPNombreIdEspecialidad(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EventSoft.ServiciosWS.listarDocentesPorCodigoPUCPNombreIdEspecialidadResponse> EventSoft.ServiciosWS.ServiciosWS.listarDocentesPorCodigoPUCPNombreIdEspecialidadAsync(EventSoft.ServiciosWS.listarDocentesPorCodigoPUCPNombreIdEspecialidadRequest request) {
            return base.Channel.listarDocentesPorCodigoPUCPNombreIdEspecialidadAsync(request);
        }
        
        public System.Threading.Tasks.Task<EventSoft.ServiciosWS.listarDocentesPorCodigoPUCPNombreIdEspecialidadResponse> listarDocentesPorCodigoPUCPNombreIdEspecialidadAsync(string nombre, int idEspecialidad) {
            EventSoft.ServiciosWS.listarDocentesPorCodigoPUCPNombreIdEspecialidadRequest inValue = new EventSoft.ServiciosWS.listarDocentesPorCodigoPUCPNombreIdEspecialidadRequest();
            inValue.nombre = nombre;
            inValue.idEspecialidad = idEspecialidad;
            return ((EventSoft.ServiciosWS.ServiciosWS)(this)).listarDocentesPorCodigoPUCPNombreIdEspecialidadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EventSoft.ServiciosWS.listarEspecialidadesTodasResponse EventSoft.ServiciosWS.ServiciosWS.listarEspecialidadesTodas(EventSoft.ServiciosWS.listarEspecialidadesTodasRequest request) {
            return base.Channel.listarEspecialidadesTodas(request);
        }
        
        public EventSoft.ServiciosWS.especialidad[] listarEspecialidadesTodas() {
            EventSoft.ServiciosWS.listarEspecialidadesTodasRequest inValue = new EventSoft.ServiciosWS.listarEspecialidadesTodasRequest();
            EventSoft.ServiciosWS.listarEspecialidadesTodasResponse retVal = ((EventSoft.ServiciosWS.ServiciosWS)(this)).listarEspecialidadesTodas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EventSoft.ServiciosWS.listarEspecialidadesTodasResponse> EventSoft.ServiciosWS.ServiciosWS.listarEspecialidadesTodasAsync(EventSoft.ServiciosWS.listarEspecialidadesTodasRequest request) {
            return base.Channel.listarEspecialidadesTodasAsync(request);
        }
        
        public System.Threading.Tasks.Task<EventSoft.ServiciosWS.listarEspecialidadesTodasResponse> listarEspecialidadesTodasAsync() {
            EventSoft.ServiciosWS.listarEspecialidadesTodasRequest inValue = new EventSoft.ServiciosWS.listarEspecialidadesTodasRequest();
            return ((EventSoft.ServiciosWS.ServiciosWS)(this)).listarEspecialidadesTodasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EventSoft.ServiciosWS.listarDocentePorIdEventoResponse EventSoft.ServiciosWS.ServiciosWS.listarDocentePorIdEvento(EventSoft.ServiciosWS.listarDocentePorIdEventoRequest request) {
            return base.Channel.listarDocentePorIdEvento(request);
        }
        
        public EventSoft.ServiciosWS.docente[] listarDocentePorIdEvento(int idEvento) {
            EventSoft.ServiciosWS.listarDocentePorIdEventoRequest inValue = new EventSoft.ServiciosWS.listarDocentePorIdEventoRequest();
            inValue.idEvento = idEvento;
            EventSoft.ServiciosWS.listarDocentePorIdEventoResponse retVal = ((EventSoft.ServiciosWS.ServiciosWS)(this)).listarDocentePorIdEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EventSoft.ServiciosWS.listarDocentePorIdEventoResponse> EventSoft.ServiciosWS.ServiciosWS.listarDocentePorIdEventoAsync(EventSoft.ServiciosWS.listarDocentePorIdEventoRequest request) {
            return base.Channel.listarDocentePorIdEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EventSoft.ServiciosWS.listarDocentePorIdEventoResponse> listarDocentePorIdEventoAsync(int idEvento) {
            EventSoft.ServiciosWS.listarDocentePorIdEventoRequest inValue = new EventSoft.ServiciosWS.listarDocentePorIdEventoRequest();
            inValue.idEvento = idEvento;
            return ((EventSoft.ServiciosWS.ServiciosWS)(this)).listarDocentePorIdEventoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EventSoft.ServiciosWS.listarActividadesPorIdEventoResponse EventSoft.ServiciosWS.ServiciosWS.listarActividadesPorIdEvento(EventSoft.ServiciosWS.listarActividadesPorIdEventoRequest request) {
            return base.Channel.listarActividadesPorIdEvento(request);
        }
        
        public EventSoft.ServiciosWS.actividad[] listarActividadesPorIdEvento(int idEvento) {
            EventSoft.ServiciosWS.listarActividadesPorIdEventoRequest inValue = new EventSoft.ServiciosWS.listarActividadesPorIdEventoRequest();
            inValue.idEvento = idEvento;
            EventSoft.ServiciosWS.listarActividadesPorIdEventoResponse retVal = ((EventSoft.ServiciosWS.ServiciosWS)(this)).listarActividadesPorIdEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EventSoft.ServiciosWS.listarActividadesPorIdEventoResponse> EventSoft.ServiciosWS.ServiciosWS.listarActividadesPorIdEventoAsync(EventSoft.ServiciosWS.listarActividadesPorIdEventoRequest request) {
            return base.Channel.listarActividadesPorIdEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EventSoft.ServiciosWS.listarActividadesPorIdEventoResponse> listarActividadesPorIdEventoAsync(int idEvento) {
            EventSoft.ServiciosWS.listarActividadesPorIdEventoRequest inValue = new EventSoft.ServiciosWS.listarActividadesPorIdEventoRequest();
            inValue.idEvento = idEvento;
            return ((EventSoft.ServiciosWS.ServiciosWS)(this)).listarActividadesPorIdEventoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EventSoft.ServiciosWS.listarEventosPorNombreResponse EventSoft.ServiciosWS.ServiciosWS.listarEventosPorNombre(EventSoft.ServiciosWS.listarEventosPorNombreRequest request) {
            return base.Channel.listarEventosPorNombre(request);
        }
        
        public EventSoft.ServiciosWS.evento[] listarEventosPorNombre(string nombre) {
            EventSoft.ServiciosWS.listarEventosPorNombreRequest inValue = new EventSoft.ServiciosWS.listarEventosPorNombreRequest();
            inValue.nombre = nombre;
            EventSoft.ServiciosWS.listarEventosPorNombreResponse retVal = ((EventSoft.ServiciosWS.ServiciosWS)(this)).listarEventosPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EventSoft.ServiciosWS.listarEventosPorNombreResponse> EventSoft.ServiciosWS.ServiciosWS.listarEventosPorNombreAsync(EventSoft.ServiciosWS.listarEventosPorNombreRequest request) {
            return base.Channel.listarEventosPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<EventSoft.ServiciosWS.listarEventosPorNombreResponse> listarEventosPorNombreAsync(string nombre) {
            EventSoft.ServiciosWS.listarEventosPorNombreRequest inValue = new EventSoft.ServiciosWS.listarEventosPorNombreRequest();
            inValue.nombre = nombre;
            return ((EventSoft.ServiciosWS.ServiciosWS)(this)).listarEventosPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EventSoft.ServiciosWS.insertarEventoResponse EventSoft.ServiciosWS.ServiciosWS.insertarEvento(EventSoft.ServiciosWS.insertarEventoRequest request) {
            return base.Channel.insertarEvento(request);
        }
        
        public int insertarEvento(EventSoft.ServiciosWS.evento evento) {
            EventSoft.ServiciosWS.insertarEventoRequest inValue = new EventSoft.ServiciosWS.insertarEventoRequest();
            inValue.evento = evento;
            EventSoft.ServiciosWS.insertarEventoResponse retVal = ((EventSoft.ServiciosWS.ServiciosWS)(this)).insertarEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EventSoft.ServiciosWS.insertarEventoResponse> EventSoft.ServiciosWS.ServiciosWS.insertarEventoAsync(EventSoft.ServiciosWS.insertarEventoRequest request) {
            return base.Channel.insertarEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EventSoft.ServiciosWS.insertarEventoResponse> insertarEventoAsync(EventSoft.ServiciosWS.evento evento) {
            EventSoft.ServiciosWS.insertarEventoRequest inValue = new EventSoft.ServiciosWS.insertarEventoRequest();
            inValue.evento = evento;
            return ((EventSoft.ServiciosWS.ServiciosWS)(this)).insertarEventoAsync(inValue);
        }
    }
}
